# safelist
branches:
  only:
  - "master"
  - "develop"
  - "issue/1/docker-compose"

os:
  - "linux"
  - "osx"

compiler:
  - "gcc"
  - "clang"

sudo: "require"

git:
  submodules: false

before_install:
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then sudo apt-get update -qq; sudo apt-get install libx11-xcb1; fi"
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi"
  - "if [ \"$TRAVIS_OS_NAME\" = \"osx\" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi"
  - "git submodule update --init --recursive"
  - "echo $PWD"
  - "git pull --all"

install:
  - "bash miniconda.sh -b -p $HOME/miniconda"
  - "export PATH=\"$HOME/miniconda/bin:$PATH\""
  - "hash -r"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "source $HOME/miniconda/etc/profile.d/conda.sh"
  - "export QT_QPA_PLATFORM='offscreen'"
  - "source install.sh"

script:
  - "cd dodo/PyDodo/ && pytest -vs tests/ && cd -"
  - "docker-compose up -d"
  - "sleep 10"
  - "docker-compose down"

after_success:
  - "test $TRAVIS_BRANCH = \"master\" && pip install mkdocs && mkdocs build --clean && mkdocs gh-deploy"
