# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: nats37

channels:
  - conda-forge

dependencies:
  - python=3.7
  - pyqt
  - numpy
  - scipy
  - matplotlib
  - pandas>=0.25.0
  - r-base
  - r-essentials
  - r-devtools
  - r-config
  - r-testthat
  - r-future
  - r-irkernel
  - r-units
  - r-geosphere

  - pip:
    - flask
    - flask_cors
    - flask_restful
    - geojson
    - jsonpath-rw-ext
    - markdown
    - mock
    - msgpack
    - python-dotenv
    - pyzmq
    - pygame
    - pyproj    # birdhouse dep
    - pyqtwebengine
    - pyopengl
    - pyopengl-accelerate
    - psutil==5.5.*
    - pytest==5.2.0
    - pytest-docker-compose
    - pylint==2.2.*
    - pylint-exit==1.0.*
    - pyqt5
    - ruamel_yaml
    - semver
    - shapely
    - wget
    - "--editable=git+https://github.com/alan-turing-institute/aviary.git@develop#egg=aviary"
